services:
  gateway:
    build: ./backend/gateway
    container_name: botflow-gateway
    ports:
      - "${GATEWAY_PORT}:8000"
    env_file:
      - .env
    networks:
      - botnet

  youtube_scraper:
    build: ./backend/scraper_youtube
    container_name: botflow-youtube
    ports:
      - "${YOUTUBE_PORT}:8080"
    env_file:
      - .env
    networks:
      - botnet

  frontend:
    build: ./frontend
    container_name: botflow-frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    env_file:
      - .env
    networks:
      - botnet
    stdin_open: true
    tty: true

networks:
  botnet:
